# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brew:
  # Repository to push the tap to.
  github:
    owner: tredfield
    name: homebrew-tap

  # Your app's homepage.
  # Default is empty.
  homepage: "https://github.com/slalom/go-slalom"

  # Your app's description.
  # Default is empty.
  description: "A golang sample webapp."
