# Azure devops pipeline. Currently runs go tests
# Add steps that build, run tests, deploy, and more: https://aka.ms/yaml

variables:
  Major: 1
  Minor: 0
  GO111MODULE: on
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
  releaseTag: $(Major).$(Minor).$(Build.BuildID)

stages:
  - stage: PullRequest
    # only run for feature branches
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
    jobs:
      - job: UnitTest
        pool:
          vmImage: 'ubuntu-latest'    
        steps:          
        - script: |
            mkdir -p '$(GOBIN)'
            mkdir -p '$(GOPATH)/pkg'
            mkdir -p '$(modulePath)'
            shopt -s extglob
            mv !(gopath) '$(modulePath)'
            echo '##vso[task.prependpath]$(GOBIN)'
            echo '##vso[task.prependpath]$(GOROOT)/bin'
          displayName: 'Set up the Go workspace'
        - script: go test -v ./...
          workingDirectory: '$(modulePath)'
          displayName: 'Run tests'
  
  # build and push image
  - stage: BuildImage
    # only run for master branch
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    jobs:
      - job: BuildAndPushImage
        pool:
          vmImage: 'ubuntu-latest'    
        steps:        
        - task: Docker@2
          displayName: 'Push Image'
          inputs:
            containerRegistry: 'go-slalom'
            repository: 'goslalom'
            command: 'buildAndPush'
            Dockerfile: 'Dockerfile'
            tags: $(releaseTag)