apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: go-slalom 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-slalom 
    spec:
      containers:
        - name: go-slalom 
          image: goslalom.azurecr.io/go-slalom 
          ports:
          - containerPort: 8090