---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-slalom
  labels:
    app: go-slalom
spec:
  replicas: 1
  selector:
    matchLabels:
     app: go-slalom
  template:
    metadata:
      labels:
        app: go-slalom
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: go-slalom
        image: go-slalom
        command:
          - go-slalom
          - start
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 5
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 10
          failureThreshold: 2
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
